#! /usr/bin/env bash

set -e

# Print the name of a temporary directory in which to build ROMS

if test -n "${1}"
then
  echo Positional arguments are not permitted
  exit 1
fi

if test -z "${ROMS_TMP}"
then
  ROMS_TMP=/tmp/${USER}
fi

if test -z "${PLATFORM}"
then
  PLATFORM=$(uname -s | cut -d "_" -f 1)-$(uname -m)
fi

# To keep the temporary directory name short, replace the full name of the
# current directory with its MD5 sum.

result=${ROMS_TMP}/roms_bld_$(uname -s -m | tr " " "-")
result=${result}_$(pwd | md5sum - | cut -d " " -f 1)

echo ${result}