#! /usr/bin/env bash

set -e

# Print the name of a temporary directory in which to build ROMS.
# The directory name encodes the current working directory.

if test -n "${1}"
then
  echo Positional arguments are not permitted
  exit 1
fi

if test -z "${ROMS_TMP}"
then
  ROMS_TMP=/tmp/${USER}
fi

result=${ROMS_TMP}/roms_bld_$(pwd | md5sum - | cut -d " " -f 1)

echo ${result}